# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('pic', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
    ]
