# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
    ]
