# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant14',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant15',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant17',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant18',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant21',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant22',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant23',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant24',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('tele', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=87)),
                ('googlecon', models.URLField(blank=True)),
            ],
        ),
    ]
