# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant10_restaurant11_restaurant12_restaurant13_restaurant14_restaurant15_restaurant16_restauran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant10',
            name='googlecon',
            field=models.CharField(blank=True, max_length=487),
        ),
        migrations.AlterField(
            model_name='restaurant11',
            name='googlecon',
            field=models.CharField(blank=True, max_length=487),
        ),
        migrations.AlterField(
            model_name='restaurant12',
            name='googlecon',
            field=models.CharField(blank=True, max_length=487),
        ),
        migrations.AlterField(
            model_name='restaurant13',
            name='googlecon',
            field=models.CharField(blank=True, max_length=487),
        ),
        migrations.AlterField(
            model_name='restaurant14',
            name='googlecon',
            field=models.CharField(blank=True, max_length=487),
        ),
        migrations.AlterField(
            model_name='restaurant15',
            name='googlecon',
            field=models.CharField(blank=True, max_length=487),
        ),
        migrations.AlterField(
            model_name='restaurant16',
            name='googlecon',
            field=models.CharField(blank=True, max_length=487),
        ),
        migrations.AlterField(
            model_name='restaurant17',
            name='googlecon',
            field=models.CharField(blank=True, max_length=487),
        ),
        migrations.AlterField(
            model_name='restaurant18',
            name='googlecon',
            field=models.CharField(blank=True, max_length=487),
        ),
        migrations.AlterField(
            model_name='restaurant19',
            name='googlecon',
            field=models.CharField(blank=True, max_length=487),
        ),
        migrations.AlterField(
            model_name='restaurant2',
            name='googlecon',
            field=models.CharField(blank=True, max_length=287),
        ),
        migrations.AlterField(
            model_name='restaurant20',
            name='googlecon',
            field=models.CharField(blank=True, max_length=487),
        ),
        migrations.AlterField(
            model_name='restaurant21',
            name='googlecon',
            field=models.CharField(blank=True, max_length=487),
        ),
        migrations.AlterField(
            model_name='restaurant22',
            name='googlecon',
            field=models.CharField(blank=True, max_length=487),
        ),
        migrations.AlterField(
            model_name='restaurant23',
            name='googlecon',
            field=models.CharField(blank=True, max_length=487),
        ),
        migrations.AlterField(
            model_name='restaurant24',
            name='googlecon',
            field=models.CharField(blank=True, max_length=487),
        ),
        migrations.AlterField(
            model_name='restaurant3',
            name='googlecon',
            field=models.CharField(blank=True, max_length=287),
        ),
        migrations.AlterField(
            model_name='restaurant4',
            name='googlecon',
            field=models.CharField(blank=True, max_length=287),
        ),
        migrations.AlterField(
            model_name='restaurant5',
            name='googlecon',
            field=models.CharField(blank=True, max_length=287),
        ),
        migrations.AlterField(
            model_name='restaurant6',
            name='googlecon',
            field=models.CharField(blank=True, max_length=487),
        ),
        migrations.AlterField(
            model_name='restaurant7',
            name='googlecon',
            field=models.CharField(blank=True, max_length=487),
        ),
        migrations.AlterField(
            model_name='restaurant8',
            name='googlecon',
            field=models.CharField(blank=True, max_length=487),
        ),
        migrations.AlterField(
            model_name='restaurant9',
            name='googlecon',
            field=models.CharField(blank=True, max_length=487),
        ),
    ]
