# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20180610_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
