from django.conf.urls import url
from .views import *

urlpatterns = (
    url(r'^restaurant1/', index),
    url(r'^restaurant2/', index2),
    url(r'^restaurant3/', index3),
    url(r'^restaurant4/', index4),
    url(r'^restaurant5/', index5),
    url(r'^restaurant6/', index6),
    url(r'^restaurant7/', index7),
    url(r'^restaurant8/', index8),
    url(r'^restaurant9/', index9),
    url(r'^restaurant10/', index10),
    url(r'^restaurant11/', index11),
    url(r'^restaurant12/', index12),
    url(r'^restaurant13/', index13),
    url(r'^restaurant14/', index14),
    url(r'^restaurant15/', index15),
    url(r'^restaurant16/', index16),
    url(r'^restaurant17/', index17),
    url(r'^restaurant18/', index18),
    url(r'^restaurant19/', index19),
    url(r'^restaurant20/', index20),
    url(r'^restaurant21/', index21),
    url(r'^restaurant22/', index22),
    url(r'^restaurant23/', index23),
    url(r'^restaurant24/', index24),
    url(r'^categorize/',categorize),
    url(r'^lottery/',lottery),
    url(r'^homepage/',homepage),
    url(r'^chinese/',chinese),
    url(r'^euro/',euro),
    url(r'^japanese/',japanese),
    url(r'^korean/',korean),
    url(r'^american/',american),
    url(r'^southeast/',southeast),

)